In [8]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])


print (a)

mean_a = np.mean(a, axis=0)

print (mean_a)



[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
[2.  8.4]


In [11]:
a_centered = a - mean_a
print(a_centered)


[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [32]:

a_centered_temp = a_centered.T

print(a_centered_temp [0])
print(a_centered_temp [1])
a_centered_sp = np.dot(a_centered_temp [0], a_centered_temp [1])
print(a_centered_sp)

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]
8.0


In [35]:
res = a_centered_sp / len(a_centered_temp[0])

print(res)

1.6
