In [52]:
import numpy as np
import sys


a = np.arange(12,25)

a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
a1 = np.hsplit(a, (2,5,7,9))

a1

[array([12, 13]),
 array([14, 15, 16]),
 array([17, 18]),
 array([19, 20]),
 array([21, 22, 23, 24])]

In [7]:
a2 = np.hsplit(a, (2,5,7,9))
#Переделать, на -1


In [ ]:
#4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
#Да.

In [16]:
sigma = 1
mu = 0

b = sigma * np.random.randn(4, 3) + mu

b

array([[-0.75087798,  0.13567504, -0.24499204],
       [ 0.22968133,  0.68294648, -0.627724  ],
       [-0.20244256,  1.44197886,  0.20772079],
       [-0.98674046, -0.21458202, -0.98458513]])

In [25]:


a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [46]:
b = np.arange(20,0,-2)
b = np.hsplit(b, 10)
b

[array([20]),
 array([18]),
 array([16]),
 array([14]),
 array([12]),
 array([10]),
 array([8]),
 array([6]),
 array([4]),
 array([2])]

In [54]:
#В чем разница между массивами a и b?
print(sys.getsizeof(a), sys.getsizeof(b))

#1. В размере занимаемой памяти. 2. b - Это лист массивов.

148 192


In [76]:
# 7. Вертикально соединить массивы a и b. a — двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
#Итоговый массив v должен иметь атрибут size, равный 10.

b = np.zeros((3,5))
b = b[0:] + 1

a = np.zeros((b.shape[0]-1,3))

b



array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
np.shape(a)

(2, 3)

In [82]:
np.shape(b)

(3, 5)

In [85]:
np.column_stack((a,b), axis=2)

TypeError: column_stack() got an unexpected keyword argument 'axis'

In [90]:
v = np.append(a, b[:, np.newaxis], axis=3)
v

AxisError: axis 3 is out of bounds for array of dimension 2